spring.application.name=apiuser

server.port=8081
# URL de conexión (formato: jdbc:postgresql://host:puerto/nombre_bd)
spring.datasource.url=jdbc:postgresql://localhost:5432/incendio

# Credenciales
spring.datasource.username=incendio
spring.datasource.password=123

# Driver (opcional en versiones modernas, Spring lo autodetecta)
spring.datasource.driver-class-name=org.postgresql.Driver