spring.application.name=apiuser

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/incendio
spring.datasource.username=incendio
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update